### Checking the local host
GET http://localhost:3000/ HTTP/1.1

### Checking the blogposts route
GET http://localhost:3000/api/blogposts/ HTTP/1.1

### Checking specific Blog post IDs
GET http://localhost:3000/api/blogposts/13 HTTP/1.1

### get all users
GET http://localhost:3000/api/user/ HTTP/1.1

### getting users by id
GET http://localhost:3000/api/user/5 HTTP/1.1

### get all todo
GET http://localhost:3000/api/todos/ HTTP/1.1

### getting todo by id
GET http://localhost:3000/api/todos/5 HTTP/1.1